language: java
jdk:
- oraclejdk8

services:
- postgresql

before_script:
- psql -c "CREATE DATABASE contacts;" -U postgres
- psql -c "CREATE USER postgres WITH PASSWORD 'postgres';" -U postgres
- psql -c "ALTER USER postgres WITH SUPERUSER;" -U postgres